version: '3.8'

services:
  mysqluserdb:
    image: mysql:8.0
    container_name: mysql-user-db
    volumes:
      - mysql-user-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=userdb
    ports:
      - "3306:3306"
  
  mysqltweetdb:
    image: mysql:8.0
    container_name: mysql-tweet-db
    volumes:
      - mysql-tweet-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tweetdb
    ports:
      - "3307:3306"
  
  mysqltagdb:
    image: mysql:8.0
    container_name: mysql-tag-db
    volumes:
      - mysql-tag-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tagdb
    ports:
      - "3308:3306"

  mysqltweettagdb:
    image: mysql:8.0
    container_name: mysql-tweettag-db
    volumes:
      - mysql-tweettag-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tweettagdb
    ports:
      - "3309:3306"

  server-registry:
    image: ttran8800/server-registry:latest
    build: ./server-registry
    container_name: server-registry
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5

  api-gateway:
    image: ttran8800/api-gateway:latest
    build: ./api-gateway
    container_name: api-gateway
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      server-registry:
        condition: service_healthy
    ports:
      - "9000:9000"

  user-service:
    image: ttran8800/user-service:latest
    build: ./user-service
    container_name: user-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      api-gateway:
        condition: service_healthy
    ports:
      - "9001:9001"

  tweet-service:
    image: ttran8800/tweet-service:latest
    build: ./tweet-service
    container_name: tweet-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      api-gateway:
        condition: service_healthy
    ports:
      - "9002:9002"
  
  tag-service:
    image: ttran8800/tag-service:latest
    build: ./tag-service
    container_name: tag-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9003/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      api-gateway:
        condition: service_healthy
    ports:
      - "9003:9003"

  tweet-tag-service:
    image: ttran8800/tweet-tag-service:latest
    build: ./tweet-tag-service
    container_name: tweet-tag-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9004/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      api-gateway:
        condition: service_healthy
    ports:
      - "9004:9004"
  
  app-tweeter-ng:
    build: ./app-tweeter-ng
    container_name: ng-tweeter
    ports:
      - "4200:80"
    depends_on:
      api-gateway:
        condition: service_healthy
    volumes:
      - /app/node_modules

volumes:
  mysql-user-data:
  mysql-tweet-data:
  mysql-tag-data:
  mysql-tweettag-data: