server:
  port: 9000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: USER-SERVICE-REGISTER
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1.0/tweets/user-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackUri: forward:/userServiceFallBack
        - id: TWEET-SERVICE
          uri: lb://TWEET-SERVICE
          predicates:
            - Path=/api/v1.0/tweets/tweet-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: TWEET-SERVICE
                fallbackUri: forward/tweetServiceFallBack
        - id: TAG-SERVICE
          uri: lb://TAG-SERVICE
          predicates:
            - Path=/api/v1.0/tweets/tag-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: TAG-SERVICE
                fallbackUri: forward/tagServiceFallBack

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://server-registry:8761/eureka

logging:
  level:
    org.springframework.web.cors: DEBUG