server:
  port: 9000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE-REGISTER
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1.0/tweets/register
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackUri: forward:/userServiceFallBack
        - id: USER-SERVICE-LOGIN
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1.0/tweets/login
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackUri: forward:/userServiceFallBack
        - id: USER-SERVICE-VALIDATE-TOKEN
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1.0/tweets/validateToken
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackUri: forward:/userServiceFallBack
        - id: TWEET-SERVICE
          uri: lb://TWEET-SERVICE
          predicates:
            - Path=/api/v1.0/tweets/**
          filters:
            - name: CircuitBreaker
              args:
                name: TWEET-SERVICE
                fallbackUri: forward/tweetServiceFallBack


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://server-registry:8761/eureka