server:
  port: 9002

spring:
  application:
    name: TWEET-SERVICE
  datasource:
    url: jdbc:mysql://mysqltweetdb:3306/tweetdb?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://server-registry:8761/eureka