apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-tweeter-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/mysql-pv"