apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-userdb-deployment
  labels:
    app: mysqluserdb
spec:
  selector:
    matchLabels:
      app: mysqluserdb
  template:
    metadata:
      labels:
        app: mysqluserdb
    spec:
      containers:
      - name: mysqluserdb
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "userdb"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec mysql -uroot -proot -e 'show databases;'
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-userdb-pvc