apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-tweeter-deployment
  labels:
    app: ng-tweeter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ng-tweeter
  template:
    metadata:
      labels:
        app: ng-tweeter
    spec:
      initContainers:
        - name: wait-for-user-service
          image: busybox:1.31
          command: ['sh', '-c', 'until nc -z -v -w30 user-service 9001; do echo "Waiting for User-Service deployment..."; sleep 5; done;']
      containers:
        - name: ng-tweeter
          image: ttran8800/ng-tweeter:latest
          ports:
            - containerPort: 80
          env:
            - name: API_GATEWAY_HOST
              value: api-gateway
            - name: API_GATEWAY_PORT
              value: "9000"
