apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-registry
  labels:
    app: server-registry
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server-registry
  template:
    metadata:
      labels:
        app: server-registry
    spec:
      containers:
      - name: server-registry
        image: ttran8800/server-registry:latest
        ports:
        - containerPort: 8761
