apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweet-service-deployment
  labels:
    app: tweet-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tweet-service
  template:
    metadata:
      labels:
        app: tweet-service
    spec:
      initContainers:
      - name: wait-for-mysql-tweetdb
        image: busybox:1.31
        command: ['sh', '-c', 'until nc -z -v -w30 mysqltweetdb 3306; do echo "Waiting for MySQL-UserDB deployment..."; sleep 5; done;']
      containers:
      - name: tweet-service
        image: ttran8800/tweet-service:latest
        ports:
        - containerPort: 9002
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9002
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
        - name: MYSQL_HOST
          value: "mysql-tweetdb-service"
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "tweetdb"
        - name: API_GATEWAY_URL
          value: "http://api-gateway:9000"