apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  labels:
    app: user-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      initContainers:
      - name: wait-for-mysql-userdb
        image: busybox:1.31
        command: ['sh', '-c', 'until nc -z -v -w30 mysqluserdb 3306; do echo "Waiting for MySQL-UserDB deployment..."; sleep 5; done;']
      containers:
      - name: user-service
        image: ttran8800/user-service:latest
        ports:
        - containerPort: 9001
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9001
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
        - name: MYSQL_HOST
          value: "mysql-userdb-service"
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "userdb"
        - name: API_GATEWAY_URL
          value: "http://api-gateway:9000"
