apiVersion: v1
kind: Service
metadata:
  name: mysqltweetdb
  labels:
    app: mysqltweetdb
spec:
  selector:
    app: mysqltweetdb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306