apiVersion: v1
kind: Service
metadata:
  name: ng-tweeter-service
spec:
  type: NodePort
  selector:
    app: ng-tweeter
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31234
      protocol: TCP