server:
  port: 9000

spring:
  profiles:
    active: native
  application:
    name: CONFIG-SERVER

eureka:
  client:
    service-url:
      defaultZone: http://server-registry:8761/eureka
  instance:
    hostname: server-registry
    prefer-ip-address: true

management:
  tracing:
    sampling:
      probability: 1.0